### ISSUE TITLE
Imported class "title" from 'styles/pages/Home.module.scss' does not exist

### ISSUE THREAD

**Issue by shawn-fetanat** [colbyfayock/next-wordpress-starter#234]
My linter complained about `styles.title` being a unresolved variable so checked out `styles/pages/Home.module.scss` since that's where `styles` was imported from and I noticed the class `title` doesn't even exist in the file. I think it's supposed to be `styles.description`. Correct if I'm wrong though. 

`Home.module.css` is a very small file. This is what it looks like:

`Home.module.css`
```scss
@import "styles/settings/__settings";

.description {
  text-align: center;
  line-height: 1.5;
  font-size: 1.5rem;
}

.posts {
  list-style: none;
  padding-left: 0;
  margin: -1rem 0;

  & > li {
    margin: 4em 0;

    &:first-child {
      margin-top: 0;
    }

    &:last-child {
      margin-bottom: 0;
    }
  }
}
``` 
Once I opened up `styles/pages/Home.module.scss` I noticed I got another error about the import being unresolved. Then I realized that was because the import  `@import "styles/settings/__settings";` is incorrect. 

The think the correct import path is `"../../styles/settings/__settings";` because the folder structure is 

```
> styles
>> components
>> pages
>>> Home.modules.scss
>> settings
>>> __settings.scss
```

Don't you have to go up to `styles` and then go down to `settings`? Again I am a newbie so I could be wrong.
